### ISSUE TITLE
Experimental Prism feature listed as runtime dependency

### ISSUE THREAD

**Issue by mhashizume** [rubocop/rubocop-ast#282] opened 2024-02-29 18:17 UTC
Support for Prism was added in rubocop-ast 1.31.0 and marked as "experimental" in the changelog. However, Prism was also added as a runtime dependency in the Gemspec.

It seems contradictory to require a library for an experimental feature, particularly when it's only available in the latest Ruby release.

We're starting to see some failures in our CI pipelines because of this new requirement.

Would you be able to remove Prism as a runtime dependency? Thank you!

**Comment by Routable** [comment] 2024-02-29 20:03
We are also experiencing this issue, with the same behavior as reported above.  Downgrading has been our solution, but this really should be addressed.

**Comment by bbatsov** [comment] 2024-02-29 20:20
Yeah, it seems we messed up. @koic I think we should move this to the `Gemfile` instead unless you have other alternatives in mind.

**Comment by marcandre** [comment] 2024-03-01 01:22
Right, I think #283 is all that is required?

**Comment by koic** [comment] 2024-03-01 02:25
This was marked as experimental with regard to the validity of what should be stable published interface API.

It seems necessary to understand the details of the issue before making a decision to remove it from the default dependencies.

RuboCop AST 0.31 requires Ruby 2.7+, and Prism works with Ruby 2.7+. This means they should be compatible in terms of requirements, and if there are any issues, it would be worth reporting to Prism:
https://github.com/ruby/prism

> We're starting to see some failures in our CI pipelines because of this new requirement.

@mhashizume @Routable Can you provide specifics about what errors are occurring?

cc @kddnewton

**Comment by marcandre** [comment] 2024-03-01 03:52
Agreed on reporting issue, but I also feel that we should not say that `rubocop-ast` _depends_ on `prism` to work.

**Comment by bbatsov** [comment] 2024-03-01 06:46
Yeah, I was under the impression that's the actual issue - now we force the installation of Prism even when it's not used. It seems to me the users will have to install Prism separately for the time being, if they want to use it.

**Comment by koic** [comment] 2024-03-01 08:37
@KNejad Thank you for the details. Let's hold off on making it a default runtime dependency until at least this installation error with Prism is resolved.

If possible, can you share that error on Prism's issue tracker?
https://github.com/ruby/prism/issues

**Closed** 2024-03-01 08:46 UTC

**Comment by VitaliySerov** [comment] 2024-03-01 10:32
> Let's hold off on making it a default runtime dependency until at least this installation error with Prism is resolved.
> If possible, can you share that error on Prism's issue tracker?


Seems this is not a bug in prism, the reason of this is that prism requires native extensions to be installed, not sure if they have any plan to remove native extensions

So probably it should be held not until prism changes something, but until rubocop releases v2.0 with respect to semantic version and breakable changes

**Comment by KNejad** [comment] 2024-03-01 11:59
Thanks for sorting this @koic!

I agree with @VitaliySerov, I don't believe this is an issue with prism. It's just they have a system dependency which isn't installed by default on some containers.
